# fly.toml app configuration file generated for cant-touch-this on 2023-09-18T12:06:25+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cant-touch-this"
primary_region = "cdg"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 1
